# Generated by Django 2.2.4 on 2020-09-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='author',
        ),
    ]
