# Generated by Django 2.2.4 on 2020-09-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200901_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
