# Generated by Django 2.2.4 on 2020-09-02 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_postimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
