# Generated by Django 2.2.4 on 2020-09-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_delete_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img3',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img4',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img5',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='post',
            name='img6',
            field=models.ImageField(blank=True, upload_to='%y/%m/%d'),
        ),
    ]
