# Generated by Django 2.2.4 on 2020-09-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200902_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='img6',
        ),
    ]
