# Generated by Django 2.2.4 on 2020-09-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200902_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
